openapi: 3.0.0
info:
   version: 1.0.0
   title: Рекламные предложения
   description: Метод описывает данные рекламных предложений, которые загружаются на странице пользователя
paths:
   /api/promotions/{msisdn}/offers:
     get:
       summary: получение рекламных предложений
       security:
         - BearerAuth: []
       parameters:
         - name: msisdn
           in: path
           description: номер телефона абонента
           required: true
           example: '79051234567'
           schema:
             type: string
         - name: inp
           in: query
           description: название рекламной акции
           required: true
           example: 'black'
           schema:
             type: string
       responses:
         '200':
           description: Положительный ответ на запрос, отображение рекламного контента
           content:
             application/json:
               schema:
                 type: object
                 properties:
                   offers:
                     type: array
                     items:
                       $ref: '#/components/schemas/offer'
                   meta:
                     $ref: '#/components/schemas/meta'
                   
         '400':
           description: Данные повреждены или допущена ошибка при неверном синтаксисе или формате данных, отправленных при запросе
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/meta'
         '401':
           description: Пользователь не авторизован или токен просрочен
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/meta'
         '404':
           description: Пользователь с указанным номером не является абонентом t2
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/meta'
         '500':
           description: По причине какого-либо внутреннего сбоя система не смогла обработать запрос
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/meta'
                
components:
   schemas:
     offer:
       type: object
       description: набор настраиваемых параметров
       properties:
         offerTheme:
           type: string
           description: название предложения
           example: 'Black'
         full_ofr_desc:
           type: string
           description: описание рекламного предложения
           example: 'Скидка при покупке в этом месяце'
         rate_with_discount:
           type: integer
           description: стоимость предложения со скидкой
           example: 299
         rate_wo_discount: 
           type: integer
           description: стоимость предложения без скидки
           example: 500
     meta:
       type: object
       properties:
         status:
           type: string
           example: 'OK'
           x-extensible-enum:
             - 'OK'
             - 'ERROR'
             - 'Unauthorized'
             - 'ERROR_MSISDN'
             - 'ERROR_PROMO'
             - 'NOT_FOUND'
             - 'SERVER_ERROR'
         message:
           type: string
           example: 'OK'
           x-extensible-enum:
             - 'BAD REQUEST'
             - 'BEARER TOKEN INVALID'
             - 'BAD MSISDN'
             - 'MSISDN NOT FOUND'
             - 'INTERNAL SERVER ERROR'
   securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
                       
                       
   
