openapi: 3.0.0
info:
   version: 1.0.0
   title: Рекламные предложения
   description: Метод описывает данные рекламных предложений, которые загружаются на странице пользователя
paths:
   /api/promotions/detail/offers:
     get:
       summary: получение рекламных предложений
       x-integration:
         type: SOAP
         operation: getSSDetailsOffer
       security:
         - BearerAuth: []
       parameters:
         - name: msisdn_id
           in: query
           description: идентификатор рекламного предложения
           required: true
           schema:
             type: integer
         - name: inp
           in: query
           description: идентификатор рекламного предложения
           required: true
           schema:
             type: integer
       responses:
         '200':
           description: Положительный ответ на запрос, отображение рекламного контента
           content:
             application/json:
               schema:
                 type: object
                 properties:
                   list:
                     type: object
                     properties:
                       treatment_id:
                         type: integer
                         description: идентификатор реклмамного предложения
                       branch_id:
                         type: integer
                         description: идентификатор региона абонента
                       sOffer_id:
                         type: integer
                         description: идентификатор абонента
                       description:
                         type: object
                         description: набор настраиваемых параметров
                         properties:
                           full_ofr_desc:
                             type: string
                             description: описание рекламного предложения
                           rate_wo_discount: 
                             type: integer
                             description: стоимость предложения без скидки
                           rate_with_discount:
                             type: integer
                             description: стоимость предложения со скидкой
                       offerType:
                         type: string
                         description: тип предложения
                       offerTheme:
                         type: string
                         description: тема оффера
                       serv_id:
                         type: integer
                         description: идентификатор услуги
                       rate_id:
                         type: integer
                         description: идентификатор тарифа
                       extension:
                         type: integer
                         description: дополнительный параметр
                       serv_id_list:
                         type: array
                         description: список с id услуг
                         items:
                           type: integer
       '401':
         description: Unauthorized
       '403':
         description: Forbidden
       '404':
         description: Not found
                
                      
                       
                       
                       
                       
                       
                       
                       
                       
                     
