openapi: 3.0.0
info:
   version: 1.0.0
   title: Рекламные предложения
   description: Метод описывает данные рекламных предложений, которые загружаются на странице пользователя
paths:
   /api/promotions/offers/{msisdn}:
     get:
       summary: получение рекламных предложений
       security:
         - BearerAuth: []
       parameters:
         - name: msisdn
           in: path
           description: номер телефона абонента
           required: true
           schema:
             type: integer
       responses:
         '200':
           description: Положительный ответ на запрос, отображение рекламного контента
           content:
             application/json:
               schema:
                 type: object
                 properties:
                   offers:
                     type: array
                     items:
                       $ref: '#/components/schemas/offer'
         '400':
           description: Bad request
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/meta'
         '401':
           description: Unauthorized
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/meta'
         '403':
           description: ERROR_MSISDN
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/meta'
         '404':
           description: Not found
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/meta'
         '500':
           description: Server error
           content:
             application/json:
               schema:
                 $ref: '#/components/schemas/meta'
                
components:
   schemas:
     offer:
       type: object
       description: набор настраиваемых параметров
       properties:
         offerTheme:
           type: string
           description: название предложения
           example: 'Black'
         full_ofr_desc:
           type: string
           description: описание рекламного предложения
           example: 'Скидка при покупке в этом месяце'
         rate_with_discount:
           type: integer
           description: стоимость предложения со скидкой
           example: 299
         rate_wo_discount: 
           type: integer
           description: стоимость предложения без скидки
           example: 500
     meta:
       type: object
       properties:
         status:
           type: string
           example: 'OK'
           x-extensible-enum:
             - 'OK'
             - 'ERROR'
             - 'Unauthorized'
             - 'ERROR_MSISDN'
             - 'NOT_FOUND'
             - 'SERVER_ERROR'
   securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
                       
                       
   
